version: '3.3'

services:
  pokemon-calculator:
    image: pokemon-calculator:latest
    networks:
      - shared_network
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  shared_network:
    external: true