"""提供 1v1 对战配置的受控枚举、机制覆盖统计和行为等价归并。"""

from pokeop.application.configuration_space.generator import (
    GenerateConfigurationSpaceUseCase,
    PokemonConfigurationGenerator,
)
from pokeop.application.configuration_space.models import (
    AbilityConfigurationCandidate,
    AbilitySpaceCommand,
    BattleConfiguration,
    ConfigurationCoverageStatistics,
    ConfigurationEquivalenceClass,
    ConfigurationSpace,
    ConfigurationSpaceError,
    ConfigurationSpaceStatistics,
    ConfigurationWeight,
    ConfigurationWeightAssumption,
    ConfiguredMove,
    GenerateConfigurationSpaceCommand,
    ItemSpaceCommand,
    MechanismCoverageRecord,
    MechanismSupportStatus,
    MoveConfigurationCandidate,
    MoveSpaceCommand,
    PokemonBattleConfiguration,
    PokemonConfigurationProfile,
    PokemonSpaceCommand,
    StatEnumerationMode,
    StatSpaceCommand,
)
from pokeop.application.configuration_space.providers import (
    AbilityDimensionProvider,
    ConfigurationDimensionProvider,
    ConfigurationDimensionValue,
    ConfigurationGenerationContext,
    DimensionExpansion,
    ItemDimensionProvider,
    MoveSetDimensionProvider,
    OpaqueDimensionValue,
    StatDimensionProvider,
)

__all__ = [
    "AbilityConfigurationCandidate",
    "AbilityDimensionProvider",
    "AbilitySpaceCommand",
    "BattleConfiguration",
    "ConfigurationCoverageStatistics",
    "ConfigurationDimensionProvider",
    "ConfigurationDimensionValue",
    "ConfigurationEquivalenceClass",
    "ConfigurationGenerationContext",
    "ConfigurationSpace",
    "ConfigurationSpaceError",
    "ConfigurationSpaceStatistics",
    "ConfigurationWeight",
    "ConfigurationWeightAssumption",
    "ConfiguredMove",
    "DimensionExpansion",
    "GenerateConfigurationSpaceCommand",
    "GenerateConfigurationSpaceUseCase",
    "ItemDimensionProvider",
    "ItemSpaceCommand",
    "MechanismCoverageRecord",
    "MechanismSupportStatus",
    "MoveConfigurationCandidate",
    "MoveSetDimensionProvider",
    "MoveSpaceCommand",
    "OpaqueDimensionValue",
    "PokemonBattleConfiguration",
    "PokemonConfigurationGenerator",
    "PokemonConfigurationProfile",
    "PokemonSpaceCommand",
    "StatDimensionProvider",
    "StatEnumerationMode",
    "StatSpaceCommand",
]
